_BASE_: "../Base_det.yaml"

MODEL:
  DETECTOR: 'GT'
  ALIGNER: 'Bezier'
  RECOGNIZER: 'PARSEQ'

DATASETS:
  TRAIN: ("ic15_train",)
  TEST: ("ic15_test",)

INPUT:
  MIN_SIZE_TRAIN: (800,900,1000,1100,1200,1300,1400)
  MAX_SIZE_TRAIN: 3000
  MIN_SIZE_TEST: 224
  MAX_SIZE_TEST: 1280
  CROP:
    ENABLED: False
  ROTATE: False

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 1e-5
  LR_BACKBONE: 1e-5
  WARMUP_ITERS: 0
  STEPS: (100000,)
  MAX_ITER: 1000
  CHECKPOINT_PERIOD: 1000

TEST:
  EVAL_PERIOD: 500
  # 1 - Generic, 2 - Weak, 3 - Strong (for icdar2015)
  LEXICON_TYPE: 1

OUTPUT_DIR: "output/vitaev2_s/150k_tt_mlt_13_15_textocr/finetune/gt_bezier_parseq"